/**
 * {@link ISelectionDialog} is an interface for user dialogues which
 * offer a selection from a list pairs of key and label generated by
 * an {@link ILabelledEntriesProvider}.
 */
package de.wwu.scdh.oxbytei.commons;

import java.util.List;

import ro.sync.ecss.extensions.api.AuthorAccess;
import ro.sync.ecss.extensions.api.AuthorOperationException;

import de.wwu.scdh.teilsp.services.extensions.ILabelledEntriesProvider;


public interface ISelectionDialog {

    /**
     * This must be called after construction in order to pass
     * initialization data.
     *
     * @param access access to the oXygen editor
     * @param multi {@code true} indicates that multiple selection
     * may should be offered to the user
     * @param currentVal current value
     * @param configured a list of initialized {@link ILabelledEntriesProvider}s
     */
    public void init(AuthorAccess access,
		     String title,
		     String multi,
		     String currentVal,
		     List<ILabelledEntriesProvider> configured)
	throws AuthorOperationException;

    /**
     * This actually does the user interaction and returns the key
     * selected by the user. {@code null} should be returned in case
     * of cancellation by the user.
     *
     * @return The key of the item selected by the user. It must
     * return {@code null} in case of cancellation by the user.
     */
    public String doUserInteraction() throws AuthorOperationException;

}
