name: Update github pages
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: run maven to get ediarum
        run: mvn --batch-mode --update-snapshots generate-sources

      - name: run maven
        run: mvn --batch-mode --update-snapshots package

      - name: create directory for github pages
        run: mkdir -p public

      - name: copy descriptor file
        run: cp target/generated-resources/xml/xslt/pom.xml public/descriptor.xml

      - name: copy index.html
        run: cp pages/index.html public/index.html

      - name: Deploy descriptor file on Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
