name: Create release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-?**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: run maven
        run: mvn -Drevision=${{github.ref_name}} -Dchangelist="" --batch-mode --update-snapshots package

      - name: create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: changeLog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: build for oxygen 23
        run: mvn -Doxygen.version=23 -Drevision=${{github.ref_name}} -Dchangelist="" --batch-mode --update-snapshots clean package

      - name: upload framework package for oxygen 23 to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: framework/target/oxbytei-oxygen23-${{ github.ref_name }}-framework.zip
          asset_name: oxbytei-oxygen23-${{ github.ref_name }}-framework.zip
          asset_content_type: application/zip

      - name: build for oxygen 24
        run: mvn -Doxygen.version=24 -Drevision=${{github.ref_name}} -Dchangelist="" --batch-mode --update-snapshots clean package

      - name: upload framework package for oxygen 24 to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: framework/target/oxbytei-oxygen24-${{ github.ref_name }}-framework.zip
          asset_name: oxbytei-oxygen24-${{ github.ref_name }}-framework.zip
          asset_content_type: application/zip

      - name: build for oxygen 25
        run: mvn -Doxygen.version=25 -Drevision=${{github.ref_name}} -Dchangelist="" --batch-mode --update-snapshots clean package

      - name: upload framework package for oxygen 25 to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: framework/target/oxbytei-oxygen25-${{ github.ref_name }}-framework.zip
          asset_name: oxbytei-oxygen25-${{ github.ref_name }}-framework.zip
          asset_content_type: application/zip

      - name: build for oxygen 26
        run: mvn -Doxygen.version=26 -Drevision=${{github.ref_name}} -Dchangelist="" --batch-mode --update-snapshots clean package

      - name: upload framework package for oxygen 26 to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: framework/target/oxbytei-oxygen26-${{ github.ref_name }}-framework.zip
          asset_name: oxbytei-oxygen26-${{ github.ref_name }}-framework.zip
          asset_content_type: application/zip
