name: Tests
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: run maven with default build profile
        run: mvn --batch-mode --update-snapshots verify

      - name: run maven with build profile for oxygen 23
        run: mvn -Doxygen.version=23 --batch-mode --update-snapshots clean verify

      - name: run maven with build profile for oxygen 23
        run: mvn -Doxygen.version=24 --batch-mode --update-snapshots clean verify

      - name: run maven with build profile for oxygen 23
        run: mvn -Doxygen.version=25 --batch-mode --update-snapshots clean verify
